spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campaignmanager
    username: root
    password: 123
  redis:
    host: leige.work
    port: 7379
mybatis:
  config-location: classpath:mybatis/sqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8088
#  context-path: /campaign

